name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: |
          ls -la
          find . -name "Dockerfile"
          find . -name "docker-compose*.yml"

      - name: Build intent-engine
        run: docker compose -f docker-compose.min.yml build intent-engine

      - name: Build web-ui
        run: docker compose -f docker-compose.min.yml build web-ui
